
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-11-15T11:24:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe85c7b27bd943300bc6ba6206eb8692741dd7c4",
 "version": "0.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
